version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: weatherweardb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2000
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./weatherwear-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/weatherweardb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2000
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./weatherwear-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data: